/**
 * Curated icon vocabulary exposed to agents.
 *
 * Kept as a plain string tuple (no React imports) so block definitions and the
 * server-safe catalog can build Zod enums from it. The name -> component map
 * lives in `components/json-render/icons.ts`; the two are kept in sync by type.
 */
export const ICON_NAMES = [
  'sun',
  'moon',
  'cloud',
  'cloudy',
  'rain',
  'snow',
  'storm',
  'wind',
  'hot',
  'cold',
  'humidity',
  'visibility',
  'compass',
  'location',
  'calendar',
  'clock',
  'globe',
  'arrow-up',
  'arrow-down',
  'arrow-right',
  'minus',
  'check',
  'check-circle',
  'close',
  'warning',
  'info',
  'alert',
  'star',
  'heart',
  'sparkles',
  'idea',
  'search',
  'user',
  'team',
  'settings',
  'bag',
  'tag',
  'wallet',
  'chart-line',
  'chart-bar',
  'chart-pie',
  'file',
  'image',
  'external-link',
  'play',
  'pause',
  'refresh',
  'mail',
  'phone',
  'chat',
  'bell',
  'flash',
  'fire',
  'leaf',
  'home',
] as const;

/** Every icon name an agent may reference from any block that takes an `icon` prop. */
export type TIconName = (typeof ICON_NAMES)[number];
