import {
  RiAlertLine,
  RiArrowDownLine,
  RiArrowRightLine,
  RiArrowUpLine,
  RiBarChartLine,
  RiCalendarLine,
  RiChat3Line,
  RiCheckLine,
  RiCheckboxCircleLine,
  RiCloseLine,
  RiCloudLine,
  RiCloudyLine,
  RiCompass3Line,
  RiErrorWarningLine,
  RiExternalLinkLine,
  RiEyeLine,
  RiFileTextLine,
  RiFireLine,
  RiFlashlightLine,
  RiGlobalLine,
  RiHeartLine,
  RiHome5Line,
  RiImageLine,
  RiInformationLine,
  RiLeafLine,
  RiLightbulbLine,
  RiLineChartLine,
  RiMailLine,
  RiMapPinLine,
  RiMoonLine,
  RiNotification3Line,
  RiPauseLine,
  RiPhoneLine,
  RiPieChartLine,
  RiPlayLine,
  RiPriceTag3Line,
  RiRainyLine,
  RiRefreshLine,
  RiSearchLine,
  RiSettings3Line,
  RiShoppingBagLine,
  RiSnowyLine,
  RiSparklingLine,
  RiStarLine,
  RiSubtractLine,
  RiSunLine,
  RiTeamLine,
  RiTempColdLine,
  RiTempHotLine,
  RiThunderstormsLine,
  RiTimeLine,
  RiUserLine,
  RiWalletLine,
  RiWaterPercentLine,
  RiWindyLine,
  type RemixiconComponentType,
} from '@remixicon/react';
import type { TIconName } from '@/components/json-render/blocks/iconNames';

/**
 * Curated remixicon lookup. Explicit imports only — never dynamically import the
 * whole icon set, which would pull thousands of components into the bundle.
 * Typed as an exhaustive record so adding a name to `ICON_NAMES` without adding
 * a component here is a compile error.
 */
export const ICON_COMPONENTS: Record<TIconName, RemixiconComponentType> = {
  sun: RiSunLine,
  moon: RiMoonLine,
  cloud: RiCloudLine,
  cloudy: RiCloudyLine,
  rain: RiRainyLine,
  snow: RiSnowyLine,
  storm: RiThunderstormsLine,
  wind: RiWindyLine,
  hot: RiTempHotLine,
  cold: RiTempColdLine,
  humidity: RiWaterPercentLine,
  visibility: RiEyeLine,
  compass: RiCompass3Line,
  location: RiMapPinLine,
  calendar: RiCalendarLine,
  clock: RiTimeLine,
  globe: RiGlobalLine,
  'arrow-up': RiArrowUpLine,
  'arrow-down': RiArrowDownLine,
  'arrow-right': RiArrowRightLine,
  minus: RiSubtractLine,
  check: RiCheckLine,
  'check-circle': RiCheckboxCircleLine,
  close: RiCloseLine,
  warning: RiErrorWarningLine,
  info: RiInformationLine,
  alert: RiAlertLine,
  star: RiStarLine,
  heart: RiHeartLine,
  sparkles: RiSparklingLine,
  idea: RiLightbulbLine,
  search: RiSearchLine,
  user: RiUserLine,
  team: RiTeamLine,
  settings: RiSettings3Line,
  bag: RiShoppingBagLine,
  tag: RiPriceTag3Line,
  wallet: RiWalletLine,
  'chart-line': RiLineChartLine,
  'chart-bar': RiBarChartLine,
  'chart-pie': RiPieChartLine,
  file: RiFileTextLine,
  image: RiImageLine,
  'external-link': RiExternalLinkLine,
  play: RiPlayLine,
  pause: RiPauseLine,
  refresh: RiRefreshLine,
  mail: RiMailLine,
  phone: RiPhoneLine,
  chat: RiChat3Line,
  bell: RiNotification3Line,
  flash: RiFlashlightLine,
  fire: RiFireLine,
  leaf: RiLeafLine,
  home: RiHome5Line,
};

/** Resolve an agent-supplied icon name, returning null when it is unknown. */
export const resolveIcon = (name: string | null | undefined): RemixiconComponentType | null =>
  name && name in ICON_COMPONENTS ? ICON_COMPONENTS[name as TIconName] : null;
