'use client';

import { tool } from '@openai/agents';
import { z } from 'zod';
import { createWeatherSpec } from '@/lib/spec-builders/weather';
import { describeReport, summariseFailure, weatherProvider } from '@/lib/weather';
import { attachSpecToReply } from '@/tools/attachSpec';

/**
 * Current conditions and a short forecast, rendered as a card and summarised in
 * one sentence for the model to speak.
 *
 * The card is not generated by the model. `execute` fetches a typed report,
 * hands it to `createWeatherSpec` and attaches the result to the reply bubble
 * itself, so the UI is schema-valid by construction and on screen the moment the
 * tool resolves. What the model receives back is only the sentence it should
 * say — see `lib/weather/summary.ts`.
 */
const getWeather = tool({
  name: 'get_weather_for_city',
  description: [
    'Current weather and a five-day forecast for a city.',
    'This tool also renders a weather card into the conversation on its own — you do not need to describe it, and you must not read it out field by field.',
    'Speak only the short summary this tool returns back to you, in your own words, in one or two sentences.',
    'Temperatures default to Fahrenheit because the user is in the United States; pass unit "celsius" only when the user asks for metric.',
  ].join(' '),
  parameters: z.object({
    city: z.string().describe('City or place name to look up, e.g. "Santa Clara".'),
    region: z
      .string()
      .nullable()
      .describe(
        'State, province or country that disambiguates the city, e.g. "California". Pass null when the user did not say one.',
      ),
    unit: z
      .enum(['fahrenheit', 'celsius'])
      .nullable()
      .describe('Temperature scale to report in. Pass null for the Fahrenheit default.'),
  }),
  async execute({ city, region, unit }) {
    const result = await weatherProvider.getReport({
      city,
      region,
      unit: unit ?? 'fahrenheit',
    });

    if (!result.ok) {
      return summariseFailure(result.code, city);
    }

    attachSpecToReply(createWeatherSpec(result.report));

    return describeReport(result.report);
  },
});

export default getWeather;
